// Independent short copy per locale. Numbers use Intl; prices never get converted by locale.
const keys=['title','intro','price','change','updated','collected','unavailable','stale','available','high','low','week','volume','source','why','pending','disclaimer','back','games','tiktok','crossTitle','crossText','reference','session','rolling','metricsMissing','points','ounce','perUsd','description','priceTitle','detailDescription','method','cryptoNote','indexNote','fxNote','goldNote'];
const rows={
  ko:['시장 시세','암호화폐·주가지수·환율·금을 한눈에 확인하세요.','가격','변동','시세 기준','수집 시각','데이터 연결 준비 중','이전 시세 · 갱신 지연','최근 수집 시세','고가','저가','7일 변동','거래량','출처','시장 움직임의 배경','확인된 자료가 모이면 업데이트합니다.','정보 제공 목적이며 투자 권유가 아닙니다.','전체 시세','게임 충전 보기','TikTok 코인 충전','충전도 간편하게','게임 충전·기프트카드 등 238개 상품을 찾아보세요.','직전 공시 대비','전일 종가 대비','24시간','지표 데이터 준비 중','포인트','USD / 트로이온스','KRW / 1 USD','비트코인, 이더리움, S&P 500, 나스닥, 코스피, 달러 환율과 금 시세. 출처와 기준 시각을 함께 확인하세요.','{asset} 시세','{asset} 가격과 변동, 기준 시각 및 데이터 출처를 확인하세요.','시세 기준 안내','미국 달러 기준 가격입니다. 24시간 지표는 제공되는 경우에만 표시합니다.','지수 값은 통화 금액이 아닌 포인트입니다. 나스닥은 종합지수를 뜻합니다.','ECB 일별 기준 환율을 달러 기준으로 환산한 값입니다. 은행 환전·실시간 거래 환율과 다릅니다.','금 1트로이온스당 미국 달러 가격입니다. 국내 소매 금값·세금은 포함하지 않습니다.'],
  en:['Markets','Crypto, indices, currencies and gold at a glance.','Price','Change','As of','Retrieved','Data connection pending','Earlier quote · update delayed','Latest collected quote','High','Low','7-day change','Volume','Source','Market context','Updates appear when verified sources are available.','For information only. Not investment advice.','All markets','Browse game top-ups','Recharge TikTok Coins','Top up, simply','Explore 238 top-up, game key and gift card options.','Vs previous reference rate','Vs previous close','24 hours','Metrics not yet available','points','USD / troy oz','KRW / 1 USD','Bitcoin, Ethereum, S&P 500, Nasdaq, KOSPI, USD/KRW and gold prices, with sources and observation times.','{asset} price','Check the {asset} price, change, observation time and data source.','About these prices','Prices are in US dollars. Rolling 24-hour metrics appear only when supplied.','Indices are measured in points, not currency. Nasdaq refers to the Composite Index.','Daily ECB reference rates converted to a US dollar base. These are not live trading or bank exchange rates.','US dollars per troy ounce of gold. Local retail premiums and taxes are excluded.'],
  ja:['マーケット','暗号資産・株価指数・為替・金の値動きを確認。','価格','騰落率','データ基準','取得日時','データ連携準備中','更新待ち・前回の価格','直近の取得価格','高値','安値','7日間の変化','出来高','出典','市場の背景','確認できた情報が揃い次第、掲載します。','情報提供を目的としており、投資を推奨するものではありません。','マーケット一覧','ゲームチャージを見る','TikTokコインをチャージ','チャージも手軽に','チャージ・ゲームキー・ギフトカードなど238商品。','前回の公表値比','前日終値比','24時間','指標データ準備中','ポイント','米ドル / トロイオンス','韓国ウォン / 1米ドル','ビットコイン、イーサリアム、S&P 500、ナスダック、KOSPI、ドル・ウォン、金の価格を出典・基準日時とともに確認。','{asset}の価格','{asset}の価格、騰落率、基準日時、データの出典を確認できます。','価格の見方','価格は米ドル建てです。24時間の指標はデータがある場合のみ表示します。','指数の単位は通貨ではなくポイントです。ナスダックは総合指数を指します。','ECBの日次参考レートを米ドル基準で算出しています。リアルタイムや銀行の両替レートではありません。','金1トロイオンス当たりの米ドル価格です。小売価格の上乗せ分や税金は含みません。'],
  'zh-tw':['市場行情','快速查看加密貨幣、股價指數、匯率與黃金。','價格','漲跌幅','資料時間','擷取時間','資料串接中','更新延遲・顯示先前報價','最近擷取報價','最高','最低','7日漲跌幅','成交量','來源','市場動態背景','待資料確認後更新。','僅供資訊參考，不構成投資建議。','所有行情','查看遊戲儲值','儲值 TikTok 金幣','輕鬆找到儲值選項','瀏覽238項儲值、遊戲序號與禮物卡商品。','較前次參考匯率','較前日收盤','24小時','指標資料準備中','點','美元 / 金衡盎司','韓元 / 1美元','查看比特幣、以太幣、S&P 500、那斯達克、KOSPI、美元兌韓元及黃金行情，附資料來源與時間。','{asset}行情','查看{asset}價格、漲跌幅、資料時間與來源。','報價說明','價格以美元計價。有提供資料時才顯示24小時指標。','指數單位為點，不是貨幣。那斯達克指綜合指數。','依ECB每日參考匯率換算成美元基準，並非即時交易或銀行換匯價格。','每金衡盎司黃金的美元價格，不含零售加價與稅費。'],
  'es-419':['Mercados','Cripto, índices, divisas y oro de un vistazo.','Precio','Variación','Fecha del dato','Consulta','Datos por conectar','Cotización anterior · actualización pendiente','Última cotización consultada','Máximo','Mínimo','Variación de 7 días','Volumen','Fuente','Contexto del mercado','Publicaremos novedades cuando haya fuentes verificadas.','Solo información. No es asesoría de inversión.','Todos los mercados','Ver recargas de juegos','Recargar monedas de TikTok','Encuentra tu próxima recarga','Explora 238 opciones de recarga, claves y tarjetas de regalo.','Vs. referencia anterior','Vs. cierre anterior','24 horas','Indicadores aún no disponibles','puntos','USD / onza troy','KRW / 1 USD','Precios de Bitcoin, Ethereum, S&P 500, Nasdaq, KOSPI, dólar a won y oro, con fuentes y fecha del dato.','Precio de {asset}','Consulta el precio de {asset}, su variación, fecha y fuente.','Cómo leer los datos','Precios en dólares de EE. UU. Las métricas de 24 horas solo se muestran si están disponibles.','Los índices se expresan en puntos, no en moneda. Nasdaq corresponde al índice compuesto.','Referencia diaria del BCE convertida a base dólar. No es un tipo de cambio bancario ni una cotización en vivo.','Dólares por onza troy de oro. No incluye impuestos ni recargos de venta al público.'],
  'es-es':['Mercados','Cripto, índices, divisas y oro en un vistazo.','Precio','Variación','Fecha del dato','Consultado','Conexión de datos pendiente','Cotización anterior · actualización pendiente','Última cotización consultada','Máximo','Mínimo','Variación en 7 días','Volumen','Fuente','Contexto del mercado','Añadiremos novedades cuando haya fuentes contrastadas.','Información general, no asesoramiento de inversión.','Todos los mercados','Ver recargas de juegos','Recargar monedas de TikTok','Recarga de forma sencilla','Consulta 238 opciones de recarga, claves y tarjetas regalo.','Frente a la referencia anterior','Frente al cierre anterior','24 horas','Indicadores aún no disponibles','puntos','USD / onza troy','KRW / 1 USD','Cotizaciones de Bitcoin, Ethereum, S&P 500, Nasdaq, KOSPI, dólar/won y oro con fuentes y fecha de referencia.','Cotización de {asset}','Consulta la cotización de {asset}, su variación, fecha de referencia y fuente.','Sobre estas cotizaciones','Precios en dólares estadounidenses. Los datos de 24 horas solo se muestran cuando están disponibles.','Los índices se expresan en puntos, no en moneda. Nasdaq se refiere al índice compuesto.','Tipo de referencia diario del BCE convertido a dólares. No es una cotización en tiempo real ni un tipo de cambio bancario.','Dólares por onza troy de oro. No incluye márgenes minoristas ni impuestos.'],
  'pt-br':['Mercados','Cripto, índices, câmbio e ouro em um só lugar.','Preço','Variação','Data do dado','Coleta','Conexão de dados pendente','Cotação anterior · atualização pendente','Última cotação coletada','Máxima','Mínima','Variação em 7 dias','Volume','Fonte','Contexto do mercado','Atualizaremos quando houver fontes verificadas.','Conteúdo informativo. Não é recomendação de investimento.','Todos os mercados','Ver recargas de jogos','Recarregar moedas do TikTok','Encontre sua recarga','Veja 238 opções de recarga, chaves de jogos e cartões-presente.','Ante a referência anterior','Ante o fechamento anterior','24 horas','Indicadores ainda indisponíveis','pontos','USD / onça troy','KRW / 1 USD','Cotações de Bitcoin, Ethereum, S&P 500, Nasdaq, KOSPI, dólar/won e ouro, com fontes e data de referência.','Cotação de {asset}','Confira a cotação de {asset}, a variação, a data de referência e a fonte.','Sobre as cotações','Preços em dólares americanos. Indicadores de 24 horas aparecem apenas quando disponíveis.','Índices são medidos em pontos, não em moeda. Nasdaq indica o índice composto.','Referência diária do BCE convertida para dólar. Não é câmbio bancário nem cotação em tempo real.','Dólares por onça troy de ouro. Não inclui impostos nem margens do varejo.'],
  ru:['Рынки','Криптовалюты, индексы, валюты и золото — кратко.','Цена','Изменение','Дата котировки','Получено','Подключаем данные','Обновление задерживается · прежняя цена','Последняя полученная котировка','Максимум','Минимум','За 7 дней','Объём','Источник','Контекст рынка','Добавим информацию после проверки источников.','Только для информации. Не является инвестиционной рекомендацией.','Все рынки','Пополнение игр','Пополнить монеты TikTok','Пополнение без лишних шагов','238 вариантов пополнения, игровых ключей и подарочных карт.','К предыдущему справочному курсу','К предыдущему закрытию','24 часа','Показатели пока недоступны','пункты','USD / тройская унция','KRW / 1 USD','Курсы Bitcoin, Ethereum, S&P 500, Nasdaq, KOSPI, доллара к воне и золота с источниками и временем котировки.','Курс {asset}','Цена {asset}, изменение, дата котировки и источник данных.','О котировках','Цены указаны в долларах США. Показатели за 24 часа отображаются только при наличии данных.','Индексы измеряются в пунктах, а не в валюте. Nasdaq означает составной индекс.','Дневной справочный курс ЕЦБ пересчитан к доллару США. Это не биржевая котировка в реальном времени и не курс банка.','Доллары США за тройскую унцию золота. Розничные наценки и налоги не включены.']
};
export const marketCopy=Object.fromEntries(Object.entries(rows).map(([l,row])=>{if(row.length!==keys.length)throw new Error('Incomplete market copy: '+l);return[l,Object.fromEntries(keys.map((k,i)=>[k,row[i]]))];}));
export const names={
 ko:['비트코인','이더리움','S&P 500','나스닥 종합','코스피','달러/원 환율','금'],
 en:['Bitcoin','Ethereum','S&P 500','Nasdaq Composite','KOSPI','USD/KRW','Gold'],
 ja:['ビットコイン','イーサリアム','S&P 500','ナスダック総合','KOSPI','米ドル／韓国ウォン','金'],
 'zh-tw':['比特幣','以太幣','S&P 500','那斯達克綜合','KOSPI','美元／韓元','黃金'],
 'es-419':['Bitcoin','Ethereum','S&P 500','Nasdaq Composite','KOSPI','Dólar / won surcoreano','Oro'],
 'es-es':['Bitcoin','Ethereum','S&P 500','Nasdaq Composite','KOSPI','Dólar / won surcoreano','Oro'],
 'pt-br':['Bitcoin','Ethereum','S&P 500','Nasdaq Composite','KOSPI','Dólar / won sul-coreano','Ouro'],
 ru:['Биткоин','Эфириум','S&P 500','Nasdaq Composite','KOSPI','Доллар / южнокорейская вона','Золото']
};
