export const weeklyCopy={
  "ko": {
    "title": "이번 주 시장 요약",
    "intro": "수집 시점의 가격과 이전 수집 대비 변동, 공식 발표와 일정을 확인하세요.",
    "period": "주간 수집 스냅샷",
    "change": "지난 수집 대비 변동률",
    "updated": "마지막 업데이트",
    "pending": "주간 데이터 준비 중",
    "retained": "같은 주차의 이전 검증값",
    "issues": "최근 공식 발표",
    "contextNote": "공통 거시 이슈입니다. 개별 자산의 등락 원인으로 단정하지 않습니다.",
    "noIssues": "확인된 발표만 표시합니다. 이슈 수를 맞추기 위해 내용을 만들지 않습니다.",
    "next": "다음 주 체크할 일정",
    "calendarNote": "BLS·연준 공식 일정입니다. 날짜는 미국 동부 기준이며, 실적 발표 일정은 아직 수집하지 않습니다.",
    "noEvents": "연결된 공식 자료에서 해당 주의 일정을 확인하지 못했습니다.",
    "history": "지난 주 요약",
    "edition": "주차별 요약",
    "latest": "최신 주간 요약",
    "fxMethod": "최신 ECB 기준환율을 수집합니다. USD 환산 기준값이며 거래 가능한 실시간 환율이 아닙니다.",
    "incomplete": "일부 데이터가 아직 연결되지 않았습니다. 빈 값은 0이 아닙니다.",
    "detailTitle": "{asset} 주간 요약",
    "description": "수집 시점의 가격과 이전 수집 대비 변동, 공식 발표와 일정을 확인하세요.",
    "original": "공식 발표 원문",
    "checked": "확인된 발표",
    "cpi": "미국 소비자물가지수(CPI)",
    "ppi": "미국 생산자물가지수(PPI)",
    "employment": "미국 고용보고서",
    "fed": "연준 통화정책 발표",
    "fomc": "FOMC 회의 마지막 날",
    "jolts": "미국 구인·이직 보고서",
    "trade-prices": "미국 수출입물가지수",
    "employment-cost": "미국 고용비용지수",
    "current": "현재가",
    "previous": "지난 정상 수집 가격",
    "baseline": "기준 가격 수집 완료",
    "nextBaseline": "다음 주부터 주간 변동을 표시합니다.",
    "method": "주 1회 수집한 가격입니다. 실제 수집 시점 간 변동이며 고정 7일 수익률이 아닙니다.",
    "observed": "공급자 기준 시각",
    "previousTime": "이전 수집 시각",
    "stale": "오래된 데이터 · 직전 정상값 유지"
  },
  "en": {
    "title": "This week in markets",
    "intro": "Collected prices, changes since the previous collection, official releases and dates to watch.",
    "period": "Weekly collection snapshot",
    "change": "Change since previous collection",
    "updated": "Last updated",
    "pending": "Weekly data pending",
    "retained": "Earlier verified data for this week",
    "issues": "Recent official releases",
    "contextNote": "Shared macro context, not a claim about what caused an asset to rise or fall.",
    "noIssues": "Only verified releases appear. We do not invent items to fill a quota.",
    "next": "Next week: dates to watch",
    "calendarNote": "Official BLS and Fed dates, in US Eastern time. Earnings calendars are not yet collected.",
    "noEvents": "No dates for this week could be verified in the connected official sources.",
    "history": "Previous weeks",
    "edition": "Weekly editions",
    "latest": "Latest weekly recap",
    "fxMethod": "Latest ECB reference rate, converted to USD base. Not a live executable exchange rate.",
    "incomplete": "Some data is not connected yet. A dash does not mean zero.",
    "detailTitle": "{asset}: weekly recap",
    "description": "Collected prices, changes since the previous collection, official releases and dates to watch.",
    "original": "Official release",
    "checked": "Verified release",
    "cpi": "US consumer prices (CPI)",
    "ppi": "US producer prices (PPI)",
    "employment": "US employment report",
    "fed": "Federal Reserve monetary policy",
    "fomc": "FOMC meeting: final day",
    "jolts": "US job openings (JOLTS)",
    "trade-prices": "US import and export prices",
    "employment-cost": "US employment costs",
    "current": "Current price",
    "previous": "Previous successful collection",
    "baseline": "Baseline collected",
    "nextBaseline": "Weekly changes will appear from next week.",
    "method": "Prices collected once a week. Changes compare actual collection times, not a fixed seven-day return.",
    "observed": "Provider observation",
    "previousTime": "Previous collection time",
    "stale": "Stale data · last successful value retained"
  },
  "ja": {
    "title": "今週のマーケットまとめ",
    "intro": "取得価格、前回取得からの変化、公式発表と注目日程を確認。",
    "period": "週次取得スナップショット",
    "change": "前回取得からの変化率",
    "updated": "最終更新",
    "pending": "週間データ準備中",
    "retained": "同じ週の確認済みデータ",
    "issues": "最近の公式発表",
    "contextNote": "共通のマクロ経済情報です。個別資産の値動きの原因を断定するものではありません。",
    "noIssues": "確認できた発表のみ掲載します。件数を埋めるための情報は作りません。",
    "next": "来週の注目日程",
    "calendarNote": "BLS・FRBの公式日程。日時は米国東部時間です。企業決算日程は未収集です。",
    "noEvents": "接続中の公式資料では、この週の日程を確認できませんでした。",
    "history": "過去の週",
    "edition": "週別まとめ",
    "latest": "最新の週間まとめ",
    "fxMethod": "最新のECB参考レートを米ドル基準に換算。リアルタイムの取引レートではありません。",
    "incomplete": "一部のデータは準備中です。「—」はゼロを意味しません。",
    "detailTitle": "{asset}の週間まとめ",
    "description": "取得価格、前回取得からの変化、公式発表と注目日程を確認。",
    "original": "公式発表の原文",
    "checked": "確認済みの発表",
    "cpi": "米国消費者物価指数（CPI）",
    "ppi": "米国生産者物価指数（PPI）",
    "employment": "米国雇用統計",
    "fed": "FRBの金融政策発表",
    "fomc": "FOMC会合最終日",
    "jolts": "米国求人・離職統計",
    "trade-prices": "米国輸出入物価指数",
    "employment-cost": "米国雇用コスト指数",
    "current": "現在価格",
    "previous": "前回の正常取得価格",
    "baseline": "基準価格を取得しました",
    "nextBaseline": "来週から週間の変化を表示します。",
    "method": "週1回取得した価格です。実際の取得時点間の変化で、固定7日間の収益率ではありません。",
    "observed": "提供元の基準日時",
    "previousTime": "前回取得日時",
    "stale": "古いデータ・前回の正常値を保持"
  },
  "zh-tw": {
    "title": "本週市場摘要",
    "intro": "查看取得價格、較上次取得變化、官方發布與重要日程。",
    "period": "每週價格快照",
    "change": "較上次取得漲跌幅",
    "updated": "最後更新",
    "pending": "每週資料準備中",
    "retained": "同週先前已確認的資料",
    "issues": "近期官方發布",
    "contextNote": "共通總體經濟資訊，不代表個別資產漲跌的確定原因。",
    "noIssues": "僅列出已確認的發布，不為湊足數量而生成內容。",
    "next": "下週關注日程",
    "calendarNote": "BLS與聯準會官方日程，採美東時間。尚未收集企業財報日程。",
    "noEvents": "目前串接的官方來源中，未能確認該週日程。",
    "history": "歷週摘要",
    "edition": "每週摘要",
    "latest": "最新每週摘要",
    "fxMethod": "最新ECB參考匯率，換算為美元基準，並非即時可交易匯率。",
    "incomplete": "部分資料尚未串接。「—」不代表零。",
    "detailTitle": "{asset}每週摘要",
    "description": "查看取得價格、較上次取得變化、官方發布與重要日程。",
    "original": "官方發布原文",
    "checked": "已確認的發布",
    "cpi": "美國消費者物價指數（CPI）",
    "ppi": "美國生產者物價指數（PPI）",
    "employment": "美國就業報告",
    "fed": "聯準會貨幣政策發布",
    "fomc": "FOMC會議最後一天",
    "jolts": "美國職缺與勞工流動調查",
    "trade-prices": "美國進出口物價指數",
    "employment-cost": "美國就業成本指數",
    "current": "目前價格",
    "previous": "上次成功取得價格",
    "baseline": "基準價格已取得",
    "nextBaseline": "下週起顯示每週變化。",
    "method": "每週取得一次價格。比較實際取得時間，並非固定七日報酬率。",
    "observed": "來源資料時間",
    "previousTime": "上次取得時間",
    "stale": "資料已過期・保留上次正常值"
  },
  "es-419": {
    "title": "Resumen semanal de mercados",
    "intro": "Precios recopilados, cambios desde la recopilación anterior, publicaciones oficiales y próximas fechas.",
    "period": "Registro semanal de precios",
    "change": "Cambio desde la recopilación anterior",
    "updated": "Última actualización",
    "pending": "Datos semanales pendientes",
    "retained": "Datos verificados anteriores de esta semana",
    "issues": "Publicaciones oficiales recientes",
    "contextNote": "Contexto macroeconómico compartido; no explica por sí solo las alzas o bajas de cada activo.",
    "noIssues": "Solo mostramos anuncios verificados. No inventamos temas para completar una lista.",
    "next": "Qué seguir la próxima semana",
    "calendarNote": "Fechas oficiales del BLS y la Fed, en horario del este de EE. UU. Aún no recopilamos resultados empresariales.",
    "noEvents": "No pudimos verificar fechas para esta semana en las fuentes oficiales conectadas.",
    "history": "Semanas anteriores",
    "edition": "Resúmenes semanales",
    "latest": "Último resumen semanal",
    "fxMethod": "Último tipo de referencia del BCE convertido a base USD; no es una cotización operable en tiempo real.",
    "incomplete": "Algunos datos están pendientes. Un guion no significa cero.",
    "detailTitle": "{asset}: resumen semanal",
    "description": "Precios recopilados, cambios desde la recopilación anterior, publicaciones oficiales y próximas fechas.",
    "original": "Anuncio oficial",
    "checked": "Anuncio verificado",
    "cpi": "Inflación de EE. UU. (CPI)",
    "ppi": "Precios al productor de EE. UU. (PPI)",
    "employment": "Empleo de EE. UU.",
    "fed": "Política monetaria de la Fed",
    "fomc": "Reunión del FOMC: último día",
    "jolts": "Vacantes de EE. UU. (JOLTS)",
    "trade-prices": "Precios de importación y exportación de EE. UU.",
    "employment-cost": "Costos laborales de EE. UU.",
    "current": "Precio actual",
    "previous": "Último precio recopilado correctamente",
    "baseline": "Precio de referencia registrado",
    "nextBaseline": "Los cambios semanales se mostrarán a partir de la próxima semana.",
    "method": "Precios recopilados una vez por semana. Se comparan las fechas reales, no un rendimiento fijo de siete días.",
    "observed": "Fecha del proveedor",
    "previousTime": "Recopilación anterior",
    "stale": "Datos desactualizados · último valor válido conservado"
  },
  "es-es": {
    "title": "La semana en los mercados",
    "intro": "Precios recogidos, variaciones desde la recogida anterior, publicaciones oficiales y próximas fechas.",
    "period": "Registro semanal de precios",
    "change": "Variación desde la recogida anterior",
    "updated": "Última actualización",
    "pending": "Datos semanales pendientes",
    "retained": "Datos anteriores verificados de esta semana",
    "issues": "Publicaciones oficiales recientes",
    "contextNote": "Contexto macroeconómico común; no atribuye causas a la subida o bajada de cada activo.",
    "noIssues": "Solo incluimos publicaciones contrastadas. No inventamos temas para completar una lista.",
    "next": "La agenda de la próxima semana",
    "calendarNote": "Fechas oficiales del BLS y la Fed, en hora del este de EE. UU. Aún no recopilamos calendarios de resultados empresariales.",
    "noEvents": "No hemos podido verificar citas para esta semana en las fuentes oficiales conectadas.",
    "history": "Semanas anteriores",
    "edition": "Resúmenes por semana",
    "latest": "Último resumen semanal",
    "fxMethod": "Último tipo de referencia del BCE convertido a base USD; no es un tipo negociable en tiempo real.",
    "incomplete": "Algunos datos están pendientes. Un guion no significa cero.",
    "detailTitle": "{asset}: resumen de la semana",
    "description": "Precios recogidos, variaciones desde la recogida anterior, publicaciones oficiales y próximas fechas.",
    "original": "Publicación oficial",
    "checked": "Publicación contrastada",
    "cpi": "IPC de Estados Unidos (CPI)",
    "ppi": "Precios de producción de EE. UU. (PPI)",
    "employment": "Informe de empleo de EE. UU.",
    "fed": "Política monetaria de la Fed",
    "fomc": "Reunión del FOMC: último día",
    "jolts": "Vacantes de EE. UU. (JOLTS)",
    "trade-prices": "Precios de importación y exportación de EE. UU.",
    "employment-cost": "Costes laborales de EE. UU.",
    "current": "Precio actual",
    "previous": "Último precio recogido correctamente",
    "baseline": "Precio de referencia guardado",
    "nextBaseline": "Las variaciones semanales se mostrarán a partir de la próxima semana.",
    "method": "Precios recogidos una vez por semana. Se comparan las fechas reales, no una rentabilidad fija de siete días.",
    "observed": "Fecha del proveedor",
    "previousTime": "Recogida anterior",
    "stale": "Datos desactualizados · se conserva el último valor válido"
  },
  "pt-br": {
    "title": "A semana nos mercados",
    "intro": "Preços coletados, variação desde a coleta anterior, divulgações oficiais e próximas datas.",
    "period": "Registro semanal de preços",
    "change": "Variação desde a coleta anterior",
    "updated": "Última atualização",
    "pending": "Dados semanais pendentes",
    "retained": "Dados anteriores verificados da mesma semana",
    "issues": "Divulgações oficiais recentes",
    "contextNote": "Contexto macroeconômico comum. Não determina a causa da alta ou queda de cada ativo.",
    "noIssues": "Exibimos apenas divulgações verificadas, sem inventar itens para completar a lista.",
    "next": "Agenda da próxima semana",
    "calendarNote": "Datas oficiais do BLS e do Fed, no horário do leste dos EUA. Calendários de balanços ainda não são coletados.",
    "noEvents": "Não foi possível confirmar datas desta semana nas fontes oficiais conectadas.",
    "history": "Semanas anteriores",
    "edition": "Resumos semanais",
    "latest": "Resumo semanal mais recente",
    "fxMethod": "Última taxa de referência do BCE convertida para base USD; não é uma cotação negociável em tempo real.",
    "incomplete": "Alguns dados ainda estão pendentes. Um traço não significa zero.",
    "detailTitle": "{asset}: resumo semanal",
    "description": "Preços coletados, variação desde a coleta anterior, divulgações oficiais e próximas datas.",
    "original": "Divulgação oficial",
    "checked": "Divulgação verificada",
    "cpi": "Inflação dos EUA (CPI)",
    "ppi": "Preços ao produtor dos EUA (PPI)",
    "employment": "Relatório de emprego dos EUA",
    "fed": "Política monetária do Fed",
    "fomc": "Reunião do FOMC: último dia",
    "jolts": "Vagas de emprego dos EUA (JOLTS)",
    "trade-prices": "Preços de importação e exportação dos EUA",
    "employment-cost": "Custos de emprego dos EUA",
    "current": "Preço atual",
    "previous": "Último preço coletado com sucesso",
    "baseline": "Preço de referência registrado",
    "nextBaseline": "As variações semanais serão exibidas a partir da próxima semana.",
    "method": "Preços coletados uma vez por semana. A comparação usa os horários reais, não um retorno fixo de sete dias.",
    "observed": "Data do provedor",
    "previousTime": "Coleta anterior",
    "stale": "Dados desatualizados · último valor válido mantido"
  },
  "ru": {
    "title": "Рынки за неделю",
    "intro": "Собранные цены, изменения с предыдущего сбора, официальные публикации и календарь.",
    "period": "Еженедельный снимок цен",
    "change": "Изменение с предыдущего сбора",
    "updated": "Обновлено",
    "pending": "Недельные данные ожидаются",
    "retained": "Ранее проверенные данные за ту же неделю",
    "issues": "Последние официальные публикации",
    "contextNote": "Общий макроэкономический контекст, а не утверждение о причинах роста или падения активов.",
    "noIssues": "Только проверенные публикации. Мы не придумываем пункты ради количества.",
    "next": "Календарь следующей недели",
    "calendarNote": "Официальные даты BLS и ФРС по восточному времени США. Даты корпоративной отчётности пока не собираются.",
    "noEvents": "В подключённых официальных источниках не удалось подтвердить даты для этой недели.",
    "history": "Прошлые недели",
    "edition": "Еженедельные выпуски",
    "latest": "Последний недельный обзор",
    "fxMethod": "Последний справочный курс ЕЦБ в пересчёте на базу USD. Это не торговый курс в реальном времени.",
    "incomplete": "Часть данных пока недоступна. Прочерк не означает ноль.",
    "detailTitle": "{asset}: итоги недели",
    "description": "Собранные цены, изменения с предыдущего сбора, официальные публикации и календарь.",
    "original": "Официальная публикация",
    "checked": "Проверенная публикация",
    "cpi": "Потребительские цены США (CPI)",
    "ppi": "Цены производителей США (PPI)",
    "employment": "Занятость в США",
    "fed": "Денежно-кредитная политика ФРС",
    "fomc": "Заседание FOMC: последний день",
    "jolts": "Вакансии США (JOLTS)",
    "trade-prices": "Импортные и экспортные цены США",
    "employment-cost": "Стоимость рабочей силы США",
    "current": "Текущая цена",
    "previous": "Цена предыдущего успешного сбора",
    "baseline": "Базовая цена сохранена",
    "nextBaseline": "Недельные изменения появятся со следующей недели.",
    "method": "Цены собираются раз в неделю. Сравниваются фактические моменты сбора, а не фиксированный семидневный период.",
    "observed": "Дата данных поставщика",
    "previousTime": "Предыдущий сбор",
    "stale": "Устаревшие данные · сохранено последнее корректное значение"
  }
};
export const finishCopy={
  "ko": {
    "more": "추가 시장 데이터 준비 중",
    "pending": "주간 데이터 연결 준비 중",
    "stale": "직전 정상 데이터 · 기준 주",
    "updated": "업데이트",
    "crossTitle": "게임 충전도 합리적으로",
    "crossText": "238개 게임 할인 충전 보기"
  },
  "en": {
    "more": "More market data coming soon",
    "pending": "Weekly data coming soon",
    "stale": "Last verified data · week of",
    "updated": "Updated"
  },
  "ja": {
    "more": "追加の市場データは準備中です",
    "pending": "週間データを準備中",
    "stale": "前回の確認済みデータ・対象週",
    "updated": "更新"
  },
  "zh-tw": {
    "more": "更多市場資料準備中",
    "pending": "每週資料準備中",
    "stale": "上次確認資料・統計週",
    "updated": "更新"
  },
  "es-419": {
    "more": "Próximamente, más datos de mercado",
    "pending": "Datos semanales en preparación",
    "stale": "Últimos datos verificados · semana del",
    "updated": "Actualizado"
  },
  "es-es": {
    "more": "Próximamente, más datos de mercado",
    "pending": "Datos semanales en preparación",
    "stale": "Últimos datos verificados · semana del",
    "updated": "Actualizado"
  },
  "pt-br": {
    "more": "Mais dados de mercado em breve",
    "pending": "Dados semanais em preparação",
    "stale": "Últimos dados verificados · semana de",
    "updated": "Atualizado"
  },
  "ru": {
    "more": "Скоро — данные других рынков",
    "pending": "Недельные данные готовятся",
    "stale": "Последние проверенные данные · неделя с",
    "updated": "Обновлено"
  }
};
