export const commerceCopy={
 en:{save:'Save up to 25% when available',offerNote:'Offers vary by country and account. Check the price on TikTok.',search:'Game recharge',placeholder:'Search games…',popular:'Popular games',all:'All products',recharge:'Recharge',buy:'View product',benefit:'Top up',sticky:'Recharge TikTok Coins',whyTitle:'Why use the Ten link?',whyText:'Purchases through Ten links may count toward extra coupons and community rewards.',whyReturn:'Use the same link each time you recharge.',showMore:'Show more products',gameIntro:'Choose your pack on the recharge page.',how:'How to recharge',steps:['Open the recharge page.','Choose your server and pack.','Check your details and pay.'],footer:'TikTok coins & game recharge',faq:'Before you recharge'},
 ko:{save:'혜택 적용 시 최대 25% 절약',offerNote:'국가와 계정에 따라 혜택이 다릅니다. 가격은 TikTok에서 확인하세요.',search:'게임 충전',placeholder:'게임 이름 검색…',popular:'인기 게임',all:'전체 상품',recharge:'충전하기',buy:'상품 보기',benefit:'게임 충전',sticky:'틱톡 코인 충전하기',whyTitle:'Ten 전용 링크를 이용하는 이유',whyText:'전용 링크의 구매 실적을 기준으로 추가 쿠폰과 커뮤니티 혜택이 제공될 수 있습니다.',whyReturn:'충전할 때마다 같은 링크를 이용해 주세요.',showMore:'상품 더 보기',gameIntro:'충전 페이지에서 원하는 상품을 선택하세요.',how:'충전 방법',steps:['전용 충전 페이지로 이동합니다.','서버와 충전 상품을 선택합니다.','계정 정보와 금액을 확인하고 결제합니다.'],footer:'틱톡 코인 · 게임 충전',faq:'충전 전 확인하세요'},
 ja:{save:'対象の場合、最大25%お得に',offerNote:'国やアカウントにより条件が異なります。価格はTikTokでご確認ください。',search:'ゲームチャージ',placeholder:'ゲーム名で検索…',popular:'人気のゲーム',all:'すべての商品',recharge:'チャージ',buy:'商品を見る',benefit:'ゲームチャージ',sticky:'TikTokコインをチャージ',whyTitle:'Ten専用リンクを使う理由',whyText:'Tenリンクからの購入は、クーポンやコミュニティ特典の対象になる場合があります。',whyReturn:'毎回、同じリンクをご利用ください。',showMore:'商品をもっと見る',gameIntro:'チャージページでパックを選べます。',how:'チャージの流れ',steps:['専用ページを開きます。','サーバーとパックを選びます。','アカウント情報と金額を確認して支払います。'],footer:'TikTokコイン・ゲームチャージ',faq:'チャージ前の確認'},
 'zh-tw':{save:'符合活動條件時，最高可省 25%',offerNote:'優惠依地區與帳號而異，實際價格請至 TikTok 確認。',search:'遊戲儲值',placeholder:'搜尋遊戲名稱…',popular:'熱門遊戲',all:'全部商品',recharge:'前往儲值',buy:'查看商品',benefit:'遊戲儲值',sticky:'儲值 TikTok 金幣',whyTitle:'為什麼使用 Ten 專屬連結？',whyText:'透過專屬連結的購買紀錄，可能符合額外優惠券或社群活動獎勵資格。',whyReturn:'每次儲值，請使用同一個專屬連結。',showMore:'顯示更多商品',gameIntro:'前往儲值頁面，選擇需要的方案。',how:'儲值步驟',steps:['開啟專屬儲值頁面。','選擇伺服器與方案。','確認帳號資料及金額後付款。'],footer:'TikTok 金幣・遊戲儲值',faq:'儲值前須知'},
 'es-419':{rechargeTikTok:'Recargar TikTok',save:'Ahorra hasta un 25% con las ofertas disponibles',offerNote:'Las ofertas dependen de tu país y cuenta. Revisa el precio en TikTok.',search:'Recargas de juegos',placeholder:'Buscar un juego…',popular:'Juegos populares',all:'Todos los productos',recharge:'Recargar',buy:'Ver producto',benefit:'Recarga',sticky:'Recargar monedas de TikTok',whyTitle:'¿Por qué usar el enlace de Ten?',whyText:'Tus compras con los enlaces de Ten pueden contar para cupones y premios de la comunidad.',whyReturn:'Usa el mismo enlace cada vez que recargues.',showMore:'Ver más productos',gameIntro:'Elige tu paquete en la página de recarga.',how:'Cómo recargar',steps:['Abre la página de recarga.','Elige tu servidor y paquete.','Revisa tus datos y paga.'],footer:'Monedas de TikTok y recargas',faq:'Antes de recargar'},
 'es-es':{rechargeTikTok:'Recargar TikTok',save:'Ahorra hasta un 25% si hay promociones',offerNote:'Las ofertas varían según tu país y cuenta. Comprueba el precio en TikTok.',search:'Recargas de juegos',placeholder:'Busca un juego…',popular:'Juegos populares',all:'Todos los productos',recharge:'Recargar',buy:'Ver producto',benefit:'Recarga',sticky:'Recargar monedas de TikTok',whyTitle:'¿Por qué usar el enlace de Ten?',whyText:'Con los enlaces de Ten puedes optar a cupones y recompensas de la comunidad.',whyReturn:'Utiliza el mismo enlace en cada recarga.',showMore:'Ver más productos',gameIntro:'Elige tu pack en la página de recarga.',how:'Cómo recargar',steps:['Abre la página de recarga.','Selecciona tu servidor y pack.','Comprueba tus datos y paga.'],footer:'Monedas de TikTok y recargas',faq:'Antes de recargar'},
 'pt-br':{rechargeTikTok:'Recarregar TikTok',save:'Economize até 25% nas ofertas disponíveis',offerNote:'As ofertas variam por país e conta. Confira o preço no TikTok.',search:'Recargas de jogos',placeholder:'Buscar um jogo…',popular:'Jogos populares',all:'Todos os produtos',recharge:'Recarregar',buy:'Ver produto',benefit:'Recarga',sticky:'Recarregar moedas do TikTok',whyTitle:'Por que usar o link do Ten?',whyText:'Compras pelos links do Ten podem contar para cupons extras e recompensas da comunidade.',whyReturn:'Use o mesmo link sempre que recarregar.',showMore:'Ver mais produtos',gameIntro:'Escolha seu pacote na página de recarga.',how:'Como recarregar',steps:['Abra a página de recarga.','Escolha seu servidor e pacote.','Confira seus dados e pague.'],footer:'Moedas do TikTok e recargas',faq:'Antes de recarregar'},
 ru:{rechargeTikTok:'Пополнить TikTok',save:'Экономия до 25% при наличии акции',offerNote:'Условия зависят от страны и аккаунта. Проверьте цену в TikTok.',search:'Пополнение игр',placeholder:'Поиск по названию игры…',popular:'Популярные игры',all:'Все товары',recharge:'Пополнить',buy:'К товару',benefit:'Пополнение',sticky:'Пополнить монеты TikTok',whyTitle:'Зачем использовать ссылку Ten?',whyText:'Покупки по ссылке Ten могут дать купоны и награды сообщества.',whyReturn:'Пополняйте по одной и той же ссылке.',showMore:'Показать ещё',gameIntro:'Выберите пакет на странице пополнения.',how:'Как пополнить',steps:['Откройте страницу пополнения.','Выберите сервер и пакет.','Проверьте данные и оплатите.'],footer:'Монеты TikTok и пополнение игр',faq:'Перед пополнением'}
};

// Keep answers short; regional account details remain in the game-page metadata.
const answers={
en:['TikTok handles coin purchases. Game links open the exact product on LootBar.','Offers depend on your country and account. Check the final price before paying.','Payments and support are handled by the provider. We do not take payment here.'],
ko:['코인은 TikTok에서, 게임은 연결된 LootBar 상품 페이지에서 충전합니다.','국가와 계정에 따라 달라집니다. 결제 전 최종 가격을 확인하세요.','결제와 주문 지원은 해당 서비스에서 담당합니다. 이곳에서는 결제하지 않습니다.'],
ja:['コインはTikTok、ゲームはリンク先のLootBarで購入できます。','国やアカウントによって異なります。支払い前に最終価格をご確認ください。','決済と注文サポートは購入先が担当します。このサイトでは決済しません。'],
'zh-tw':['金幣在 TikTok 購買；遊戲則前往對應的 LootBar 商品頁儲值。','優惠依地區與帳號而異，付款前請確認最終價格。','付款與訂單問題由銷售平台處理，本網站不收款。'],
'es-419':['Las monedas se compran en TikTok. Los juegos se recargan en la página de LootBar.','Depende de tu país y cuenta. Revisa el precio final antes de pagar.','El proveedor gestiona el pago y tu pedido. Aquí no se realizan pagos.'],
'es-es':['Las monedas se compran en TikTok. Los enlaces de juegos abren el producto en LootBar.','Depende de tu país y cuenta. Comprueba el importe final antes de pagar.','El proveedor gestiona el pago y la atención del pedido. Aquí no se cobra.'],
'pt-br':['Compre moedas no TikTok. Os links dos jogos abrem o produto na LootBar.','Depende do país e da conta. Confira o preço final antes de pagar.','O fornecedor cuida do pagamento e do pedido. Este site não recebe pagamentos.'],
ru:['Монеты покупают в TikTok. Игровые ссылки открывают нужный товар на LootBar.','Условия зависят от страны и аккаунта. Проверьте итоговую цену до оплаты.','Оплатой и заказами занимается поставщик. На этом сайте оплата не принимается.']};
export function shortenFaq(locales){for(const [l,a] of Object.entries(answers))locales[l].faqItems=locales[l].faqItems.map(([q],i)=>[q,a[i]]);}
