import {viewCounter} from './page-views.mjs';
export function iconHead(origin){return `<link rel="icon" href="/icons/recharge-v3.svg" type="image/svg+xml"><link rel="icon" href="/icons/favicon-32x32.png?v=3" sizes="32x32" type="image/png"><link rel="icon" href="/icons/favicon-16x16.png?v=3" sizes="16x16" type="image/png"><link rel="shortcut icon" href="/favicon.ico?v=3"><link rel="apple-touch-icon" href="/icons/apple-touch-icon.png?v=3" sizes="180x180"><link rel="manifest" href="/site.webmanifest?v=3"><meta name="theme-color" content="#176347"><meta property="og:image" content="${origin}/icons/recharge-og-v3.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Coupon Countdown — TikTok coins and game recharge">`;}
import {underMaintenance,maintenanceLabels,catalogOrder} from './availability.mjs';
import {marketCopy} from './markets/locales.mjs';
import { locales, localeOrder } from './locales.mjs';
export const TIKTOK='https://www.tiktok.com/coin?rc=MNN8WQ8P';
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fill=(s,g)=>s.replaceAll('{game}',g);
const arrow='<span aria-hidden="true">↗</span>';
const bolt='<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="26" fill="#176347"/><path d="M35 13 20 35h11l-2 16 16-24H34z" fill="#fff"/></svg>';
export function gameName(g,lang){return g.names?.[lang]||g.names?.en||g.name;}
const route=(l,g)=>g?.marketPath?`/${l}/${g.marketPath}`:`/${l}/${g?`games/${g.slug}/`:''}`;
function outbound(url,label,kind,pos,game='',name='') {return `<a class="button ${kind==='tiktok'?'button-tiktok':''}" href="${escape(url)}" target="_blank" rel="sponsored noopener" data-outbound="${kind}" data-position="${pos}" data-game="${escape(game)}" data-name="${escape(name)}">${label} ${arrow}</a>`;}
function productCTA(g,l,label,pos){return underMaintenance(g)?`<button class="button maintenance" disabled data-maintenance="true" data-game="${g.slug}" data-name="${escape(gameName(g,l))}" data-destination="${escape(g.url)}">${maintenanceLabels[l]}</button>`:outbound(g.url,label,'lootbar',pos,g.slug,gameName(g,l));}
export function header(l,g){const t=locales[l];return `<a class="skip" href="#main">${t.skip}</a><header class="header shell"><a class="brand" href="/${l}/" aria-label="Coupon Countdown ${t.home}"><span class="brand-mark">${bolt}</span><span>coupon<span class="brand-light">countdown</span></span></a><nav aria-label="${t.games}"><a class="nav-games" href="/${l}/#games">${t.games}</a><details class="language"><summary><span aria-hidden="true">◎</span> ${t.label} <span aria-hidden="true">⌄</span></summary><div class="language-menu">${localeOrder.filter(k=>locales[k]).map(k=>`<a href="${route(k,g)}" lang="${locales[k].tag}" hreflang="${locales[k].tag}" data-language="${k}" ${k===l?'aria-current="true"':''}>${locales[k].label}</a>`).join('')}</div></details></nav></header>`;}
function card(g,l,pos){const t=locales[l],name=gameName(g,l);return `<article class="game-card" data-slug="${g.slug}" data-category="${g.category}" data-availability="${underMaintenance(g)?'maintenance':'available'}" data-search="${escape([name,g.name,g.slug,...Object.values(g.names||{}),...(g.aliases||[])].join(' '))}"><a class="game-art" href="${route(l,g)}" tabindex="-1" aria-hidden="true"><img src="${g.localImage}" srcset="${g.smallImage} 160w, ${g.localImage} 320w" sizes="(max-width: 650px) 45vw, (max-width: 1100px) 23vw, 190px" alt="" width="320" height="320" loading="lazy" decoding="async"></a><div class="game-body"><h3><a href="${route(l,g)}">${escape(name)}</a></h3><p>${g.category==='top-up'?t.benefit:t[g.category==='game-key'?'keys':'gifts']}</p>${productCTA(g,l,g.category==='top-up'?t.recharge:t.buy,pos)}</div></article>`;}
function linkReason(t){return `<aside class="link-reason"><h2>${t.whyTitle}</h2><p>${t.whyText}<br>${t.whyReturn}</p></aside>`;}
function faq(t,items){return `<section class="faq shell"><div><span class="section-kicker">FAQ</span><h2>${t.faq}</h2></div><div>${items.map(([q,a])=>`<details><summary>${escape(q)}<span aria-hidden="true">+</span></summary><p>${escape(a)}</p></details>`).join('')}</div></section>`;}
export function footer(l){const t=locales[l];return `<footer class="shell">${viewCounter(l)}<div class="footer-top"><a class="brand" href="/${l}/">${bolt}<span>couponcountdown</span></a><span>${t.footer}</span></div><p>${t.affiliate}</p><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} Coupon Countdown</span><a href="/${l}/markets/">${marketCopy[l].title}</a><a href="/${l}/privacy/">${t.privacy}</a><button class="text-button" data-analytics-settings>${t.settings}</button></div></footer><aside class="consent" hidden><p>${t.consent}</p><button data-consent="yes">${t.allow}</button><button data-consent="no">${t.decline}</button></aside>`;}
function sticky(l,g){const t=locales[l];return `<aside class="mobile-sticky">${g?productCTA(g,l,g.category==='top-up'?t.recharge:t.buy,'sticky'):outbound(TIKTOK,t.sticky,'tiktok','sticky')}</aside>`;}
export function head(l,title,description,path,origin,assets,extra={}){const t=locales[l];return `<!doctype html><html lang="${t.tag}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} | Coupon Countdown</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${origin}/${l}/${path}">${localeOrder.filter(k=>locales[k]).map(k=>`<link rel="alternate" hreflang="${locales[k].tag}" href="${origin}/${k}/${path}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin}/en/${path}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${origin}/${l}/${path}">${iconHead(origin)}<link rel="stylesheet" href="${assets.css}"><script type="module" src="${assets.js}"></script>${assets.stats?`<script type="module" src="${assets.stats}"></script>`:''}</head><body data-locale="${l}" data-results="${escape(t.searchCount)}" data-filtered-title="${escape(t.filteredTitle)}" data-all-title="${escape(t.all)}" data-ga="${escape(extra.ga||'')}">`;}
function ld(data){return `<script type="application/ld+json">${JSON.stringify(data).replaceAll('<','\\u003c')}</script>`;}
export function home(l,games,origin,assets,ga){const t=locales[l];const popular=['kingshot','genshin-impact','whiteout-survival','last-war-survival','tiles-survive','honkai-star-rail'].map(slug=>games.find(g=>g.slug===slug)).filter(g=>g&&!underMaintenance(g));return head(l,t.title,t.description,'',origin,assets,{ga})+header(l)+`<main id="main"><section class="tiktok shell" aria-labelledby="tiktok-heading"><div class="tiktok-content"><h1 id="tiktok-heading">${t.tiktok}</h1><p class="saving">${t.save}</p><div class="hero-actions">${outbound(TIKTOK,t.rechargeTikTok,'tiktok','hero')}</div><p class="offer-note">${t.offerNote}</p></div><div class="hero-service" aria-hidden="true"><span class="coin-symbol">♪</span><span>TikTok</span></div></section><section class="catalog shell" id="games"><div class="search-top"><div><h2>${t.search}</h2></div><span class="catalog-total">${games.length} ${t.countLabel}</span></div><div class="search-wrap"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" stroke-width="1.7"/><path d="m16 16 5 5" stroke="currentColor" stroke-width="1.7"/></svg><input type="search" id="game-search" autocomplete="off" placeholder="${t.placeholder}" aria-label="${t.search}" aria-controls="all-grid"><button class="clear-search" hidden aria-label="${t.clear}">×</button><span class="search-key" aria-hidden="true">/</span></div><div class="quick-picks"><span>${t.suggested}</span>${popular.slice(0,4).map(g=>`<button data-query="${escape(gameName(g,l))}">${escape(gameName(g,l))}</button>`).join('')}</div><section id="popular"><div class="section-heading"><div><h2>${t.popular}</h2></div><a href="#all-games">${t.all} <span aria-hidden="true">↓</span></a></div><div class="game-grid popular-grid">${popular.map(g=>card(g,l,'popular')).join('')}</div></section><section class="recent-section" hidden><h2>${t.recent}</h2><div class="recent-list"></div></section>${linkReason(t)}<section id="all-games"><div class="section-heading"><h2 id="all-heading">${t.all}</h2><span id="result-count" role="status" aria-live="polite">${games.length} ${t.countLabel}</span></div><div class="filters" role="group" aria-label="${t.games}">${[['all',t.allTab],['top-up',t.topups],['game-key',t.keys],['gift-card',t.gifts]].map(([v,n])=>`<button data-filter="${v}" aria-pressed="${v==='all'}">${n}</button>`).join('')}</div><div class="game-grid" id="all-grid">${catalogOrder(games).map(g=>card(g,l,'catalog')).join('')}</div><button class="show-more" data-show-more hidden>${t.showMore}</button><div class="empty" hidden><h3>${t.noResults}</h3><button data-reset>${t.clear}</button></div></section></section>${faq(t,t.faqItems)}</main>${footer(l)}${sticky(l)}${ld({'@context':'https://schema.org','@type':'WebSite',name:'Coupon Countdown',url:origin+'/'+l+'/',inLanguage:t.tag})}</body></html>`;}
export function detail(l,g,games,origin,assets,ga){const t=locales[l],name=gameName(g,l),over=g.content?.[l]||{},title=over.title||fill(g.category==='top-up'?t.gameTitle:g.category==='game-key'?t.keyTitle:t.giftTitle,name),description=over.description||(g.category==='top-up'?fill(t.gameDescription,name):title+'. '+t.keyIntro),faqs=over.faq||(g.category==='top-up'?t.gameFaq.map(x=>x.map(y=>fill(y,name))):t.faqItems);return head(l,title,description,`games/${g.slug}/`,origin,assets,{ga})+header(l,g)+`<main id="main" class="detail-main"><div class="shell"><a class="breadcrumb" href="/${l}/#games">← ${t.back}</a><section class="product"><img class="product-art" src="${g.localImage}" alt="${escape(name)}" width="320" height="320" fetchpriority="high"><div><span class="section-kicker">${t[g.category==='top-up'?'topups':g.category==='game-key'?'keys':'gifts']}</span><h1>${escape(over.h1||fill(g.category==='top-up'?t.gameH1:t[g.category==='game-key'?'keyTitle':'giftTitle'],name))}</h1><p class="product-intro">${underMaintenance(g)?maintenanceLabels[l]:g.category==='top-up'?t.gameIntro:t.keyIntro}</p>${productCTA(g,l,over.cta||(g.category==='top-up'?t.recharge:t.buy),'detail_hero')}<p class="product-note">${underMaintenance(g)?maintenanceLabels[l]:t.onLootbar+' '+arrow}</p></div></section>${linkReason(t)}${g.category==='top-up'?`<section class="steps"><h2>${t.how}</h2><ol>${t.steps.map(s=>`<li>${s}</li>`).join('')}</ol></section>`:''}</div>${faq(t,faqs)}<section class="shell related"><h2>${t.related}</h2><div class="game-grid">${games.filter(x=>x.category===g.category&&x.slug!==g.slug).slice(0,6).filter(x=>!underMaintenance(x)).map(x=>card(x,l,'related')).join('')}</div></section></main>${footer(l)}${sticky(l,g)}${ld({'@context':'https://schema.org','@type':'WebPage',name:title,description,url:origin+route(l,g),inLanguage:t.tag,mainEntity:{'@type':'Thing',name},breadcrumb:{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:t.home,item:origin+'/'+l+'/'},{'@type':'ListItem',position:2,name,item:origin+route(l,g)}]}})}${ld({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))})}</body></html>`;}
export function privacy(l,origin,assets,ga){const t=locales[l];return head(l,t.privacy,t.privacyText,'privacy/',origin,assets,{ga})+header(l)+`<main id="main" class="shell privacy"><h1>${t.privacy}</h1><p>${t.privacyText}</p><p>${t.affiliate}</p><button data-analytics-settings>${t.settings}</button></main>`+footer(l)+'</body></html>';}
